name: Create a comment on new issue

on:
  issues:
    types: [opened]
  
jobs:
  comment-with-action:
    runs-on: label-demo
    steps:
      - name: "Dump GitHub Context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: ${{ toJSON(github.event.issue.number) }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
